package uz.doston.flyingbookbot.enums;

public enum State {
    USER_ANONYMOUS, USER_LANG, USER_FULL_NAME, USER_AGE, USER_GENDER, USER_PHONE_NUMBER, USER_AUTHORIZED,
    CHANGE_NAME, CHANGE_AGE, CHANGE_LANGUAGE, CHANGE_NUMBER, CHANGE_LIMIT,
    REMOVE_NAME, SEARCH_NAME, SEARCH_GENRE,
    ADD_FILE, ADD_GENRE,
    ADD_REMOVE_MANAGER,
    DELETE_ALL,
    UNDEFINED;
}
